INSERT INTO company (id, name, location_selector, header_selector, content_selector, url, type) VALUES
(1, 'Amazon', 'ul.association-content li', '.title', 'div.container > div > div > div.content', 'https://amazon.jobs', 'Big Tech'),
(2, 'Stripe', 'div.JobDetailCardProperty:nth-child(1) > div:nth-child(2) > p:nth-child(2)', '.JobsDetail__header > header:nth-child(1) > h1:nth-child(1)', '.ArticleMarkdown', 'https://stripe.com/jobs', 'Fintech'),
(3, 'Google', 'div.op1BBf:nth-child(2) > span:nth-child(2) > span:nth-child(2)', '.p1N2lc', '.DkhPwc', 'https://careers.google.com', 'Big Tech'),
(4, 'Revolut', 'span.HStack-rui__sc-4zbgg7-0:nth-child(1) > span:nth-child(2)', 'h1.Box-rui__sc-1g1k12l-0', '.sc-a7e7675-1', 'https://revolut.com/careers', 'Fintech'),
(5, 'Adyen', 'div.ds-font-weight-bold', '.ds-heading', '.gh-description', 'https://careers.adyen.com', 'Fintech'),
(6, 'Checkout.com', '.css-cygeeu > div:nth-child(1) > dl:nth-child(2) > dd:nth-child(2)', '.css-7papts', '.css-oplht1', 'https://checkout.com/careers', 'Fintech'),
(7, 'Visa', 'div.vs-col-12:nth-child(2) > p:nth-child(1)', '.vs-h1', '#skipTo > vs-careers-detail:nth-child(2)', 'https://usa.visa.com/careers.html', 'Fintech'),
(8, 'Mastercard', 'div.job-other-info > span:nth-child(2) > span:nth-child(1)', 'h1.job-title', '.jd-info', 'https://careers.mastercard.com', 'Fintech'),
(9, 'American Express', 'p.position-location:nth-child(1) > span:nth-child(1)', 'h1.position-title', '.position-job-description-column > div:nth-child(1)', 'https://aexp.eightfold.ai/careers', 'Fintech'),
(10, 'Wise', 'li.Locations-wrapper:nth-child(3)', '#headertext', '#d71d0450-2e94-4acc-8c9e-8bdb8ea99c9d', 'https://wise.jobs', 'Fintech'),
(11, 'Paypal', 'div.position-location-12ZUO', '.position-title-3TPtN', '.container-3Gm1a', 'https://paypal.eightfold.ai/careers', 'Fintech'),
(12, 'Datadog', 'p.tw-text-center:nth-child(1)', 'h2.tw-font-semibold', 'div.tw-px-4:nth-child(3)', 'https://careers.datadoghq.com/all-jobs/', 'Infrastructure'),
(13, 'Snowflake', '.job-other-info > span:nth-child(1) > span:nth-child(1)', 'h1.job-title', '.jd-info', 'https://careers.snowflake.com', 'Infrastructure'),
(14, 'Microsoft', '.position-location-12ZUO', '.position-title-3TPtN', '.container-3Gm1a', 'https://apply.careers.microsoft.com/careers', 'Big Tech'),
(15, 'Meta', 'div.xx4vt8u:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > span:nth-child(2)', 'h1.x16g9bbj', 'div.xx4vt8u:nth-child(1) > div:nth-child(1)', 'https://www.metacareers.com/jobsearch/', 'Big Tech'),
(16, 'Apple', '#jobdetails-joblocation', '#jobdetails-postingtitle', 'section.hyperlink-underline', 'https://jobs.apple.com/en-us/search', 'Big Tech'),
(17, 'Oracle', '.job-details__subtitle > span:nth-child(1)', 'h1.heading:nth-child(2)', '.component-styling-wrapper-108030 > div:nth-child(2)', 'https://careers.oracle.com', 'Big Tech'),
(18, 'Netflix', NULL, NULL, NULL, 'https://jobs.netflix.com', 'Big Tech'),
(19, 'Nvidia', NULL, NULL, NULL, 'https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite', 'Big Tech'),
(20, 'X', NULL, NULL, NULL, 'https://careers.x.com', 'Big Tech'),
(21, 'Block', '.css-1ye4lh5 > span:nth-child(3) > span:nth-child(1)', '.css-noh4ak', '.css-7isutc', 'https://block.xyz/careers', 'Fintech'),
(22, 'Plaid', '.css-13bevm7 > div:nth-child(3)', '.css-1jmtdzv', '.css-3wjmih', 'https://plaid.com/careers', 'Fintech'),
(23, 'Airwallex', '.single-job-locations', '.elementor-element-be6503b > div:nth-child(1) > h1:nth-child(1)', '#job-content > div:nth-child(1)', 'https://careers.airwallex.com/jobs', 'Fintech'),
(24, 'GoCardless', NULL, NULL, NULL, 'https://gocardless.com/careers', 'Payment Infrastructure'),
(25, 'TrueLayer', 'div._1tsacb60:nth-child(2) > div:nth-child(2) > div:nth-child(2)', '.ar6vju4e', '._12nvjk70', 'https://truelayer.com/careers', 'Payment Infrastructure'),
(26, 'Modulr', NULL, NULL, NULL, 'https://modulrfinance.com/careers', 'Payment Infrastructure'),
(27, 'Form3', 'p.mt-2', 'h1.mb-6', 'div.job-content:nth-child(1)', 'https://www.form3.tech/careers/vacancies', 'Payment Infrastructure'),
(28, 'Primer', NULL, NULL, NULL, 'https://primer.io/careers', 'Payment Infrastructure'),
(29, 'Marqeta', 'div.md\:block:nth-child(3)', '.font-semibold', '.md\:pl-8', 'https://marqeta.com/company/careers', 'Payment Infrastructure'),
(30, 'Databricks', '.h4', '.mb-2\.5 > div:nth-child(1)', '.b2', 'https://www.databricks.com/company/careers/open-positions', 'Infrastructure'),
(31, 'Cloudflare', '.job__location > div:nth-child(2)', 'h1.section-header', '.job__description', 'https://www.cloudflare.com/careers/jobs/', 'Infrastructure'),
(32, 'MongoDB', NULL, NULL, NULL, 'https://mongodb.com/careers', 'Infrastructure'),
(33, 'Twilio', '.job__location > div:nth-child(2)', 'h1.section-header', '.job__description', 'https://twilio.com/company/jobs', 'Infrastructure'),
(34, 'JPMorgan', '.job-details__subtitle > span:nth-child(1)', 'h1.heading:nth-child(2)', '.component-styling-wrapper-89157 > div:nth-child(2)', 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs', 'Finance & Banking'),
(35, 'Goldman Sachs', '.gs-uitk-c-10wunp9--text-root', '.gs-uitk-c-lzsmqw--text-root', '.gs-uitk-c-3o8nai--text-root > div:nth-child(1) > div:nth-child(1)', 'https://higher.gs.com/results?&page=1&sort=RELEVANCE', 'Finance & Banking'),
(36, 'Morgan Stanley', '.position-location-12ZUO', '.position-title-3TPtN', '.container-3Gm1a', 'https://morganstanley.eightfold.ai/careers?start=0', 'Finance & Banking'),
(37, 'Bloomberg', 'article.article:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)', '.article__content__view__field__value--font > div:nth-child(1)', '.tf_replaceFieldVideoTokens > div:nth-child(1) > div:nth-child(1)', 'https://bloomberg.avature.net/careers/SearchJobs', 'Finance & Banking'),
(38, 'LSEG', NULL, NULL, NULL, 'https://lseg.com/careers', 'Finance & Banking'),
(39, 'Bank of America', NULL, NULL, NULL, 'https://careers.bankofamerica.com', 'Finance & Banking'),
(40, 'Citi', NULL, NULL, NULL, 'https://jobs.citi.com', 'Finance & Banking'),
(41, 'HSBC', NULL, NULL, NULL, 'https://www.hsbc.com/careers', 'Finance & Banking'),
(42, 'Barclays', NULL, NULL, NULL, 'https://barclays.com/careers', 'Finance & Banking'),
(43, 'Monzo', '.job__location > div:nth-child(2)', 'h1.section-header', '.job__description', 'https://monzo.com/careers#jobs', 'Finance & Banking'),
(44, 'Starling', 'div.styles--11q6G:nth-child(1) > span:nth-child(1) > span:nth-child(1)', '.styles--2vxXd > h1:nth-child(2)', 'section.styles--3vx-H:nth-child(2)', 'https://www.starlingbank.com/careers/#jobs', 'Finance & Banking'),
(45, 'Citadel', '.single-job-application__title-inner > p:nth-child(2)', 'h1.with-animations > span:nth-child(1)', '.text', 'https://citadel.com/careers', 'Quant & AI'),
(46, 'Two Sigma', NULL, NULL, NULL, 'https://twosigma.com/careers', 'Quant & AI'),
(47, 'Jane Street', NULL, NULL, NULL, 'https://janestreet.com/join-jane-street', 'Quant & AI'),
(48, 'DE Shaw', NULL, NULL, NULL, 'https://deshaw.com/careers', 'Quant & AI'),
(49, 'Point72', NULL, NULL, NULL, 'https://careers.point72.com', 'Quant & AI'),
(50, 'Millennium', NULL, NULL, NULL, 'https://mlp.com/careers', 'Quant & AI'),
(51, 'HRT', NULL, NULL, NULL, 'https://hudsonrivertrading.com/careers', 'Quant & AI'),
(52, 'OpenAI', NULL, NULL, NULL, 'https://openai.com/careers', 'Quant & AI'),
(53, 'Anthropic', NULL, NULL, NULL, 'https://anthropic.com/careers', 'Quant & AI'),
(54, 'xAI', NULL, NULL, NULL, 'https://x.ai/careers', 'Quant & AI'),
(55, 'Brevan Howard', NULL, NULL, NULL, 'https://brevanhoward.com/careers', 'Quant & AI'),
(56, 'Marshall Wace', NULL, NULL, NULL, 'https://mwam.com/join-us', 'Quant & AI'),
(57, 'Coinbase', '.Listing__JobDescription-sc-e73b35ee-7 > div:nth-child(1) > p:nth-child(18)', '.Listing__Title-sc-e73b35ee-3', '.Listing__JobDescription-sc-e73b35ee-7 > div:nth-child(1)', 'https://www.coinbase.com/en-gb/careers/positions', 'Crypto & Prediction'),
(58, 'Kraken', NULL, NULL, NULL, 'https://kraken.com/careers', 'Crypto & Prediction'),
(59, 'Binance', NULL, NULL, NULL, 'https://binance.com/careers', 'Crypto & Prediction'),
(60, 'Polymarket', NULL, NULL, NULL, 'https://polymarket.com/careers', 'Crypto & Prediction'),
(61, 'Kalshi', 'div._section_101oc_37:nth-child(1) > p:nth-child(2)', '._title_ud4nd_34', '._descriptionText_oj0x8_198', 'https://kalshi.com/careers', 'Crypto & Prediction'),
(62, 'Uber', '.css-ghtRay', '.css-huLrFc', '.css-cvJeNJ', 'https://www.uber.com/us/en/careers/list/', 'Consumer Tech'),
(63, 'Deliveroo', 'span.text-body-strong', '.text-heading-1', '.xl\:pb-30 > div:nth-child(1) > div:nth-child(1) > div:nth-child(1)', 'https://careers.deliveroo.co.uk/join-the-team/', 'Consumer Tech'),
(64, 'Spotify', 'span.ma-0', 'h1.headline-1', 'div.mt-mobile-0:nth-child(1)', 'https://lifeatspotify.com/jobs|Consumer Tech', 'Consumer Tech'),
(65, 'Discord', NULL, NULL, NULL, 'https://discord.com/careers', 'Consumer Tech'),
(66, 'Notion', NULL, NULL, NULL, 'https://notion.so/careers', 'Consumer Tech'),
(67, 'Slack', NULL, NULL, NULL, 'https://slack.com/careers', 'Consumer Tech'),
(68, 'Shopify', NULL, NULL, NULL, 'https://shopify.com/careers', 'Consumer Tech'),
(69, 'Airbnb', NULL, NULL, NULL, 'https://careers.airbnb.com', 'Consumer Tech');
